version: '3.9'

volumes:
  postgres:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - secret-envs/postgres-credentials-initial.env
    volumes:
      - postgres:/var/lib/postgresql/data

  be: &be
    build:
      context: dockerfiles
      dockerfile: be.Dockerfile
    volumes:
      - ..:/app
    env_file:
      - secret-envs/secret-key-base.env
      - secret-envs/database-url.env
    environment:
      DEBUG: "true"
    links:
      - postgres

  django_be:
    <<: *be
    container_name: django_be
    command: >
      /bin/bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:3000"
    ports:
      - 3000:3000

  aiortc_be:
    <<: *be
    container_name: aiortc_be
    command: >
      /bin/bash -c "
      uvicorn aiortc_be.server:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   command: >
  #     /bin/sh -c "
  #     exec nginx -g 'daemon off;'"
  #   volumes:
  #     - ./datum/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 80:80
  #   links:
  #     - be
