# Generated by Django 4.1.2 on 2022-10-20 18:06

from django.db import migrations, models
import django.db.models.deletion
import ndarraydjango.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ip_cam_adress', models.CharField(max_length=20, null=True)),
                ('ip_cam_user', models.CharField(max_length=10, null=True)),
                ('ip_cam_password', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('career', models.TextField(choices=[('staff', 'staff'), ('student', 'student')], max_length=15, null=True)),
                ('image', models.FileField(null=True, upload_to='images/')),
                ('image_original_nd_array', ndarraydjango.fields.NDArrayField(editable=True, null=True, shape=128)),
                ('image_pinfase_nd_array', ndarraydjango.fields.NDArrayField(editable=True, null=True, shape=128)),
                ('image_lfw_nd_array', ndarraydjango.fields.NDArrayField(editable=True, null=True, shape=128)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybackVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(max_length=50)),
                ('video', models.FileField(upload_to='videos/')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_camera.camera')),
            ],
        ),
    ]
