# Generated by Django 4.1.2 on 2022-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image_original_nd_array',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image_pinfase_nd_array',
        ),
    ]
