# Generated by Django 4.0.6 on 2022-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
