# Generated by Django 4.1.2 on 2022-10-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0002_remove_person_image_original_nd_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbackvideo',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
