# Generated by Django 4.0.6 on 2022-07-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0002_camera_description_camera_url_alter_camera_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
