# Generated by Django 4.1.2 on 2022-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0003_alter_playbackvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbackvideo',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playbackvideo',
            name='headline',
            field=models.CharField(max_length=50),
        ),
    ]
