# Generated by Django 4.1.1 on 2022-09-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0003_alter_camera_description_alter_camera_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='url',
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_cam_adress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_cam_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_cam_user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PlaybackVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(default='')),
                ('video', models.FileField(upload_to='video/')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_camera.camera')),
            ],
        ),
    ]
