# Generated by Django 4.1.1 on 2022-09-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0004_remove_camera_url_camera_ip_cam_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('career', models.TextField(choices=[('staff', 'staff'), ('student', 'student')], max_length=15, null=True)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_cam_adress',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_cam_user',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playbackvideo',
            name='headline',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playbackvideo',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
