# Generated by Django 4.1.1 on 2022-09-21 14:16

from django.db import migrations
import ndarraydjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0005_person_alter_camera_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_nd_array',
            field=ndarraydjango.fields.NDArrayField(editable=True, null=True, shape=(96, 96, 3)),
        ),
    ]
