# Generated by Django 4.1.2 on 2022-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0005_playbackvideo_filename_alter_playbackvideo_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbackvideo',
            name='recognized',
            field=models.BooleanField(default=False),
        ),
    ]
