# Generated by Django 4.1.1 on 2022-09-27 22:34

from django.db import migrations
import ndarraydjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ai_camera', '0007_alter_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_nd_array',
            field=ndarraydjango.fields.NDArrayField(editable=True, null=True, shape=128),
        ),
    ]
